server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: battle
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: fiipractic
    password: fiipractic
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true